### PR TITLE
Add a little bit of style

### PR DESCRIPTION
**Pull request by leepfrog**
- Add a logo
- Add a GitHub mark for GitHub Link
- Add some basic style

### CODE REVIEW

**Comment by leepfrog** [comment]
I didn't spend much time on this, but I figure an incremental improvement is still an improvement :)

**Comment by leepfrog** [comment]
Screenshot 2023-07-29 at 12 43 23 PM

Ok, went a tiny bit further with it... but I think I'll leave it there (for someone else to pick up and run with!)

**Review by NullVoxPopuli — APPROVED** [review]
This is very fancy! any chance you want to make it support light mode? (color-scheme?) https://ember-primitives.pages.dev/6-utils/color-scheme

if not, that's cool, too. I can add on to your work! 🥳

**Comment by leepfrog** [comment]
Screenshot 2023-07-29 at 1 50 12 PM
Screenshot 2023-07-29 at 1 50 26 PM

I got it!

**Comment by NullVoxPopuli** [comment]
very exciting! thank you!!!

**Pull request merged**
